# Generated by Django 4.1.7 on 2023-05-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('fullname', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='Address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=255)),
                ('appointment_note', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Confirmed'), (4, 'Attended'), (5, 'Unattended'), (-1, 'Rejected')], default=1)),
                ('serial', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('dentistry', 'Dentistry'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('neurology', 'Neurology'), ('ophthalmology', 'Ophthalmology'), ('pediatrics', 'Pediatrics')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('visiting_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_appointments', models.PositiveSmallIntegerField()),
                ('booked_appointments', models.PositiveSmallIntegerField(default=0)),
                ('confirmed_appointments', models.PositiveSmallIntegerField(default=0)),
                ('attended_appointments', models.PositiveSmallIntegerField(default=0)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('otp_generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('create_time', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=255)),
                ('trx_id', models.CharField(max_length=255)),
                ('transaction_status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=255)),
                ('merchant_invoice_number', models.CharField(max_length=255)),
                ('refund_amount', models.CharField(max_length=255)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appointment')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
    ]
