# Generated by Django 4.1.7 on 2023-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('create_time', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=255)),
                ('trx_id', models.CharField(max_length=255)),
                ('transaction_status', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=255)),
                ('merchant_invoice_number', models.CharField(max_length=255)),
                ('refund_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='visiting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
